"""Closed label and dataset enums for the IAM triage experiment."""

from __future__ import annotations

from enum import StrEnum


class IssueType(StrEnum):
    SSO_AUTHENTICATION_FAILURE = "SSO_AUTHENTICATION_FAILURE"
    MFA_FAILURE = "MFA_FAILURE"
    ACCOUNT_LOCKED_OR_DISABLED = "ACCOUNT_LOCKED_OR_DISABLED"
    ACCESS_DENIED_AFTER_LOGIN = "ACCESS_DENIED_AFTER_LOGIN"
    PROVISIONING_OR_SYNC_FAILURE = "PROVISIONING_OR_SYNC_FAILURE"
    OTHER_IAM = "OTHER_IAM"


class Severity(StrEnum):
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"
    P4 = "P4"


class RoutingTeam(StrEnum):
    IDENTITY_PLATFORM = "IDENTITY_PLATFORM"
    ACCESS_MANAGEMENT = "ACCESS_MANAGEMENT"
    SERVICE_DESK = "SERVICE_DESK"


class AffectedScope(StrEnum):
    SINGLE_USER = "SINGLE_USER"
    MULTIPLE_USERS = "MULTIPLE_USERS"
    DEPARTMENT = "DEPARTMENT"
    ORGANIZATION = "ORGANIZATION"
    UNKNOWN = "UNKNOWN"


class RecommendedAction(StrEnum):
    RESET_OR_UNLOCK_ACCOUNT = "RESET_OR_UNLOCK_ACCOUNT"
    INVESTIGATE_MFA_CONFIGURATION = "INVESTIGATE_MFA_CONFIGURATION"
    INVESTIGATE_IDP_OR_SSO_CONFIGURATION = "INVESTIGATE_IDP_OR_SSO_CONFIGURATION"
    REVIEW_ACCESS_ENTITLEMENTS = "REVIEW_ACCESS_ENTITLEMENTS"
    INVESTIGATE_PROVISIONING_SYNC = "INVESTIGATE_PROVISIONING_SYNC"
    COLLECT_MORE_INFORMATION = "COLLECT_MORE_INFORMATION"
    ESCALATE_SECURITY_REVIEW = "ESCALATE_SECURITY_REVIEW"


class DatasetSplit(StrEnum):
    TRAIN = "train"
    VALIDATION = "validation"
    TEST = "test"
    ADVERSARIAL = "adversarial"


class DatasetSource(StrEnum):
    SYNTHETIC_TEMPLATE_GENERATOR = "SYNTHETIC_TEMPLATE_GENERATOR"
    HUMAN_AUTHORED = "HUMAN_AUTHORED"
    DEIDENTIFIED_PRODUCTION = "DEIDENTIFIED_PRODUCTION"


class AnnotationStatus(StrEnum):
    SYNTHETICALLY_LABELED = "SYNTHETICALLY_LABELED"
    HUMAN_ANNOTATED = "HUMAN_ANNOTATED"
    HUMAN_ADJUDICATED = "HUMAN_ADJUDICATED"


class ReviewStatus(StrEnum):
    PENDING_HUMAN_REVIEW = "PENDING_HUMAN_REVIEW"
    HUMAN_APPROVED = "HUMAN_APPROVED"
    HUMAN_REJECTED = "HUMAN_REJECTED"


class RobustnessCategory(StrEnum):
    EMOTIONAL_URGENCY = "EMOTIONAL_URGENCY"
    AMBIGUOUS_REPORT = "AMBIGUOUS_REPORT"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
    MISLEADING_TERMINOLOGY = "MISLEADING_TERMINOLOGY"
    PROMPT_INJECTION = "PROMPT_INJECTION"
    INCOMPLETE_INFORMATION = "INCOMPLETE_INFORMATION"


class DatasetPurpose(StrEnum):
    TRAINING = "training"
    VALIDATION = "validation"
    TEST_EVALUATION = "test_evaluation"
    ADVERSARIAL_EVALUATION = "adversarial_evaluation"
    ANALYSIS = "analysis"
